### ISSUE TITLE
Simplify the CSS codef or shared properties.

### ISSUE THREAD

**Issue by josephtkim** [xiangyuzhang/prj-rev-bwfs-dasmoto#5]
It is a good idea to simplify the CSS code for shared properties. Some of the properties are shared for multiple selectors, such as the font-family and font-weight properties. For instance,

```css
h1, h2, span {
  font-family: Helvetica;
  font-weight: bold;
}
```
